# Offense count: 2
# Cop supports --auto-correct.
Style/RedundantSelf:
  Exclude:
    - 'app/models/map.rb'
    - 'app/models/user.rb'

# Offense count: 23
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'Gemfile'
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/models/relationship.rb'
    - 'app/models/user.rb'
    - 'app/uploaders/image_uploader.rb'
    - 'app/uploaders/picture_uploader.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, MinSize.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  Exclude:
    - 'Gemfile'
