version: "3"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.pro
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    environment:
    # .envファイルの環境変数を呼び出す。
      - NODE_ENV=$NODE_ENV
      - RAILS_ENV=$RAILS_ENV
      - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - /var/tmp
    depends_on:
      - db
      - webpacker

  db:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      NODE_ENV: $NODE_ENV
      RAILS_ENV: $RAILS_ENV
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USERNAME: $MYSQL_USERNAME
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    environment:
      - NODE_ENV=$NODE_ENV
      - RAILS_ENV=$RAILS_ENV
    ports:
      - 80:80
    volumes:
      - ./nginx/log:/var/log/nginx
      - public-data:/app/public
    depends_on:
      - app

  webpacker:
    build:
      context: .
      dockerfile: Dockerfile.pro
    environment:
      - RAILS_ENV=$RAILS_ENV
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
      # up時、node_modulesエラー解消
      - /app/node_modules
    ports:
      - "3035:3035"

volumes:
  bundle:
  mysql_data:
  public-data: