version: "3"

services:

  

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    environment:
      - RAILS_ENV=development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - /var/tmp
    depends_on:
      - db
      - webpacker
      - chrome

  db:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp_development
      MYSQL_USERNAME: root
      RAILS_ENV: development
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/log:/var/log/nginx
      - public-data:/app/public
    depends_on:
      - app

  webpacker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - RAILS_ENV=development
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
      # up時、node_modulesエラー解消
      - /app/node_modules
    ports:
      - "3035:3035"

  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"

volumes:
  bundle:
  mysql_data:
  public-data:
  node_modules: