version: "3"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.pro
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=c1659ef76b816b4d2013768799ffd2b8
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - /var/tmp
    depends_on:
      - db

  db:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      NODE_ENV: production
      RAILS_ENV: production
      MYSQL_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp_production
      MYSQL_USERNAME: root
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
    ports:
      - 80:80
    volumes:
      - ./nginx/log:/var/log/nginx
      - public-data:/app/public
    depends_on:
      - app

volumes:
  bundle:
  mysql_data:
  public-data: